add az-devops-mlops
microsoft/light-up-azure pull request #20
Opened 2023-05-28 01:22 UTC by Anna-Jeong-MS

2023-05-30 03:04 UTC, justinyoo requested changes
이미지 중에 개인정보 드러나는 부분이 하나 있는데, 그것만 블러처리 해 주시면 좋겠습니다.

2023-05-30 03:04 UTC, justinyoo commented on 07-az-devops-mlops/images/image1.png
이메일 주소 드러나는데 괜찮으신가요?

2023-06-08 06:37 UTC, Anna-Jeong-MS commented on 07-az-devops-mlops/images/image1.png
수정하였습니다!

2023-06-09 01:24 UTC, justinyoo approved these changes

2023-06-09 01:24 UTC, merged